plugins { id 'io.micronaut.build.internal.cdi-test-suite' }

ext.mpTck = [
    component: 'telemetry-tracing',
    artifact: 'org.eclipse.microprofile.telemetry:microprofile-telemetry-tracing-tck:2.1',
    sourceClassifier: 'sources',
    framework: 'testng'
]

apply from: rootProject.file('microprofile-tck/tck.gradle')

dependencies {
    testImplementation('io.helidon.microprofile.telemetry:helidon-microprofile-telemetry:4.5.5') { exclude group: 'io.helidon.microprofile.weld', module: 'weld-se-core' }
}

dependencies {
    testImplementation 'org.eclipse.microprofile.rest.client:microprofile-rest-client-api:4.0'
    testImplementation 'org.eclipse:yasson:3.0.4'
    testImplementation 'org.eclipse.parsson:parsson:1.1.7'
}
