projectVersion=1.0.0-SNAPSHOT
projectGroup=io.micronaut.cdi

title=Micronaut CDI
projectDesc=A Jakarta Contexts and Dependency Injection Lite implementation built on Micronaut
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-cdi
developers=Denis Stepanov

org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g
predictiveTestSelection=false

coreDocsUrl=https://docs.micronaut.io/latest/api/io/micronaut/
guideUrl=https://docs.micronaut.io/latest/guide/
