/* Licensed under the Apache License, Version 2.0. */
package io.micronaut.cdi.mptck;

import java.lang.invoke.MethodHandles;
import java.nio.file.*;
import java.util.*;

/** Generated definitions need the runtime package of their host to access package-private TCK beans. */
final class GeneratedClasses {
    // Bytecode belongs to the loader that defined it. An unrelated parent loader must not be
    // mistaken for an already installed deployment; weak keys do not retain finished test loaders.
    private static final Map<ClassLoader, Map<String, byte[]>> DEFINED = new WeakHashMap<>();
    static void install(Path compiled, Set<String> archive, ClassLoader parent) throws java.io.IOException {
        Map<String, byte[]> defined;
        synchronized (DEFINED) { defined = DEFINED.computeIfAbsent(parent, ignored -> new HashMap<>()); }
        Map<String, Class<?>> anchors = new HashMap<>();
        for (String name : archive) {
            try {
                Class<?> host = Class.forName(name, false, parent);
                anchors.putIfAbsent(host.getPackageName(), host);
            } catch (ClassNotFoundException ignored) { }
        }
        Map<String, byte[]> pending = new TreeMap<>();
        try (var paths = Files.walk(compiled)) {
            for (Path file : paths.filter(p -> p.toString().endsWith(".class")).toList()) {
                String name = compiled.relativize(file).toString().replace(java.io.File.separatorChar, '.');
                name = name.substring(0, name.length() - 6);
                // The type index describes this archive, so it and its definition stay deployment-local.
                if (name.contains("CdiTypeIndex")) continue;
                byte[] known = defined.get(name);
                byte[] bytes = Files.readAllBytes(file);
                if (known != null) {
                    if (!Arrays.equals(known, bytes)) {
                        // Never silently use another deployment's bytecode. Forking a test class is required
                        // if an extension changes an already installed definition.
                        throw new IllegalStateException("HARNESS: different generated bytes for " + name + "; run this TCK class in a fresh test process");
                    }
                    continue;
                }
                try { Class.forName(name, false, parent); continue; } catch (ClassNotFoundException ignored) { }
                pending.put(name, bytes);
            }
        }
        boolean progress;
        do {
            progress = false;
            for (String name : List.copyOf(pending.keySet())) {
                int dot = name.lastIndexOf('.');
                String pkg = name.substring(0, dot);
                String simple = name.substring(dot + 1);
                if (simple.startsWith("$")) simple = simple.substring(1);
                int inner = simple.indexOf('$');
                if (inner >= 0) simple = simple.substring(0, inner);
                Class<?> host = anchors.get(pkg);
                try { host = Class.forName(pkg + "." + simple, false, parent); } catch (ClassNotFoundException ignored) { }
                if (host == null) continue; // Harness bridge and registration helpers live in the child loader.
                try {
                    byte[] bytes = pending.get(name);
                    MethodHandles.privateLookupIn(host, MethodHandles.lookup()).defineClass(bytes);
                    defined.put(name, bytes);
                    pending.remove(name);
                    progress = true;
                } catch (IllegalAccessException | LinkageError ignored) {
                    // A generated superclass may need to be installed first; retry after other definitions.
                }
            }
        } while (progress && !pending.isEmpty());
    }
}
