plugins { id 'io.micronaut.build.internal.cdi-test-suite' }

ext.mpTck = [
    component: 'telemetry-metrics',
    artifact: 'org.eclipse.microprofile.telemetry:microprofile-telemetry-metrics-tck:2.1',
    sourceClassifier: 'sources',
    framework: 'testng'
]

apply from: rootProject.file('microprofile-tck/tck.gradle')

dependencies {
    testImplementation('io.helidon.microprofile.telemetry:helidon-microprofile-telemetry:4.5.5') { exclude group: 'io.helidon.microprofile.weld', module: 'weld-se-core' }
}
